name: online_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.4.4
  # agora_rtc_engine: ^4.0.0-rc.3
  animated_text_kit: ^4.2.1
  another_flushbar: ^1.10.22
  auto_route: ^7.9.0
  avatar_glow: ^3.0.1
  bubble: ^1.2.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  date_picker_timeline: ^1.2.3
  day_night_time_picker: ^1.0.2
  dio: ^5.4.1
  equatable: ^2.0.0
  expansion_tile_card: ^3.0.0
  faker: ^2.0.0
  file_icon: ^1.0.0
  file_picker: ^5.2.10
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flick_video_player: ^0.7.0
  flutter_advanced_segment: ^3.0.2
  flutter_bloc: ^7.2.0
  # flutter_chat_ui: ^1.0.3
  flutter_downloader: ^1.6.0
  # flutter_firebase_chat_core: ^1.0.3
  flutter_inner_drawer: ^1.0.0+1
  flutter_screenutil: ^5.0.0+2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.0.6
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  get: ^4.1.4
  get_it: ^7.1.3
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  injectable: ^2.3.5
  intl: ^0.18.1
  jiffy: ^6.2.1
  # jitsi_meet: ^4.0.0
  json_annotation: ^4.0.1
  kt_dart: ^1.1.0
  lottie: ^3.1.0
  material_design_icons_flutter: ^7.0.7296
  mime: ^1.0.0
  nil: ^1.1.1
  octo_image: ^2.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  shimmer: ^3.0.0
  sleek_circular_slider: ^2.0.0
  tab_indicator_styler: ^2.0.0-null-safety
  timeago: ^3.0.2
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  cached_network_image: ^3.0.0
  freezed: ^2.4.7
  injectable_generator: ^2.5.1
  json_serializable: ^6.7.1
  video_player: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/images/
    - assets/svg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
